import type { SecurityContext } from "./types.js";

interface PhaseResult {
  ok: boolean;
  phase: "phase1" | "phase2" | "phase3";
  reason?: string;
}

const PROTECTED_PATHS = ["/etc/shadow", "/etc/sudoers", "/root/.ssh", "/etc/ssh"];

export function runSecurityPhases(ctx: SecurityContext): PhaseResult {
  const p1 = runPhase1SystemBaseline(ctx);
  if (!p1.ok) {
    return p1;
  }

  const p2 = runPhase2AssetIntegrity(ctx);
  if (!p2.ok) {
    return p2;
  }

  return runPhase3FinalConfirmation(ctx);
}

function runPhase1SystemBaseline(ctx: SecurityContext): PhaseResult {
  if (!ctx.sessionId.trim()) {
    return { ok: false, phase: "phase1", reason: "Missing session id." };
  }

  if (ctx.executorMode === "ssh" && !ctx.targetHost) {
    return { ok: false, phase: "phase1", reason: "SSH mode requires target host context." };
  }

  return { ok: true, phase: "phase1" };
}

function runPhase2AssetIntegrity(ctx: SecurityContext): PhaseResult {
  const command = ctx.command?.toLowerCase() ?? "";
  const touchingProtectedAsset = PROTECTED_PATHS.some((path) => command.includes(path));
  if (touchingProtectedAsset) {
    return { ok: false, phase: "phase2", reason: "Command touches protected system assets." };
  }

  return { ok: true, phase: "phase2" };
}

function runPhase3FinalConfirmation(ctx: SecurityContext): PhaseResult {
  // Allow longer guarded commands generated by the planner (rollback markers, idempotent branches, etc.).
  // The previous 500-char limit was too strict and caused false blocking for normal workflows.
  if (!ctx.command || ctx.command.length > 4000) {
    return { ok: false, phase: "phase3", reason: "Command is empty or exceeds the safe length limit." };
  }

  return { ok: true, phase: "phase3" };
}
